import { EditorThemeClasses } from 'lexical'

import { cn } from '@/utils/cn.ts'

export const lexicalEditorTheme: EditorThemeClasses = {
  autocomplete: 'PlaygroundEditorTheme__autocomplete',
  blockCursor: 'PlaygroundEditorTheme__blockCursor',
  characterLimit: 'PlaygroundEditorTheme__characterLimit',
  code: cn(
    'relative mx-0 my-2 block overflow-x-auto bg-[rgb(240,242,245)] py-2 pl-[52px] pr-2 text-sm',
    'before:absolute before:left-0 before:top-0 before:bg-[#eee] before:content-[attr(data-gutter)]',
    'before:min-w[25px] before:whitespace-pre-wrap before:border-r before:border-[#ccc] before:p-2 before:text-right before:text-[#777]',
  ),
  codeHighlight: {
    atrule: 'text-[#07a]',
    attr: 'text-[#07a]',
    boolean: 'text-[#905]',
    builtin: 'text-[#690]',
    cdata: 'text-[slategray]',
    char: 'text-[#690]',
    class: 'text-[#dd4a68]',
    'class-name': 'text-[#dd4a68]',
    comment: 'text-[slategray]',
    constant: 'text-[#905]',
    deleted: 'text-[#905]',
    doctype: 'text-[slategray]',
    entity: 'text-[#9a6e3a]',
    function: 'text-[#dd4a68]',
    important: 'text-[#e90]',
    inserted: 'text-[#690]',
    keyword: 'text-[#07a]',
    namespace: 'text-[#e90]',
    number: 'text-[#905]',
    operator: 'text-[#9a6e3a]',
    prolog: 'text-[slategray]',
    property: 'text-[#905]',
    punctuation: 'text-[#999]',
    regex: 'text-[#e90]',
    selector: 'text-[#690]',
    string: 'text-[#690]',
    symbol: 'text-[#905]',
    tag: 'text-[#905]',
    url: 'text-[#9a6e3a]',
    variable: 'text-[#e90]',
  },
  embedBlock: {
    base: 'PlaygroundEditorTheme__embedBlock',
    focus: 'PlaygroundEditorTheme__embedBlockFocus',
  },
  hashtag:
    'bg-[rgba(88,144,255,0.15)] border-b border-[rgba(88, 144, 255, 0.3)]',
  heading: {
    h1: 'text-4xl text-foreground font-bold my-6',
    h2: 'text-3xl text-foreground font-bold my-5',
    h3: 'text-2xl text-foreground font-bold my-4',
    h4: 'text-xl text-foreground font-bold my-3',
    h5: 'text-lg text-foreground font-bold my-2',
    h6: 'text-base text-foreground font-bold my-1',
  },
  hr: 'PlaygroundEditorTheme__hr',
  image: 'editor-image',
  indent: 'PlaygroundEditorTheme__indent',
  inlineImage: 'inline-editor-image',
  layoutContainer: 'PlaygroundEditorTheme__layoutContainer',
  layoutItem: 'PlaygroundEditorTheme__layoutItem',
  link: 'text-[rgb(33,111,219)] no-underline hover:underline cursor-pointer',
  list: {
    checklist: '',
    listitem: 'my-0 mx-8',
    listitemChecked: 'EditorTheme__listItemChecked',
    listitemUnchecked: 'EditorTheme__listItemUnChecked',
    nested: {
      listitem: 'list-none before:hidden after:hidden',
    },
    olDepth: [
      'p-0 m-0 list-outside',
      'p-0 m-0 list-outside !list-[upper-alpha]',
      'p-0 m-0 list-outside !list-[lower-alpha]',
      'p-0 m-0 list-outside !list-[upper-roman]',
      'p-0 m-0 list-outside !list-[lower-roman]',
    ],
    ul: 'p-0 m-0 list-outside list-disc',
    ol: 'p-0 m-0 list-outside list-decimal',
  },
  ltr: 'text-left',
  mark: 'PlaygroundEditorTheme__mark',
  markOverlap: 'PlaygroundEditorTheme__markOverlap',
  paragraph: 'm-0 relative',
  quote:
    'm-0 ml-5 mb-2.5 text-[15px] text-[rgb(101, 103, 107)] border-[rgb(206,208,212)] border-left-[4px] pl-4',
  rtl: 'text-right',
  table: 'PlaygroundEditorTheme__table',
  tableCell: 'PlaygroundEditorTheme__tableCell',
  tableCellActionButton: 'PlaygroundEditorTheme__tableCellActionButton',
  tableCellActionButtonContainer:
    'PlaygroundEditorTheme__tableCellActionButtonContainer',
  tableCellEditing: 'PlaygroundEditorTheme__tableCellEditing',
  tableCellHeader: 'PlaygroundEditorTheme__tableCellHeader',
  tableCellPrimarySelected: 'PlaygroundEditorTheme__tableCellPrimarySelected',
  tableCellResizer: 'PlaygroundEditorTheme__tableCellResizer',
  tableCellSelected: 'PlaygroundEditorTheme__tableCellSelected',
  tableCellSortedIndicator: 'PlaygroundEditorTheme__tableCellSortedIndicator',
  tableResizeRuler: 'PlaygroundEditorTheme__tableCellResizeRuler',
  tableSelected: 'PlaygroundEditorTheme__tableSelected',
  tableSelection: 'PlaygroundEditorTheme__tableSelection',
  text: {
    bold: 'font-bold',
    code: 'bg-[rgb(240,242,245)] py-px px-1 text-[0.94rem]',
    italic: 'italic',
    strikethrough: 'line-through decoration-wavy',
    subscript: 'text-sm align-sub',
    superscript: 'text-sm align-super',
    underline: 'underline decoration-wavy',
    underlineStrikethrough:
      '[text-decoration:underline_line-through] decoration-wavy',
  },
}
